### ISSUE TITLE
sine.jl doesn't work

### ISSUE THREAD

**Issue by sunbluesome** [aterenin/SparseGaussianProcesses.jl#1]
I tried sine.jl, but it doesn't work.

`gp` was not defined in line 6,
```julia
gp = SparseGaussianProcess(SquaredExponentialKernel(1), inducing_points = PseudoDataInducingPoints(gp.kernel, 10))
```

Because I'm a beginner for Julia, I'm not sure about your code.
Thank you.

**Comment by aterenin** [comment]
You happened to catch the example on a day where I made some tweaks to it. 🙂 

Try with the current master branch, or with `sine.jl` from the most-recent release (https://github.com/aterenin/SparseGaussianProcesses.jl/blob/v0.1.0/examples/sine.jl). 

Let me know if that works.

**Comment by sunbluesome** [comment]
What timing:sweat_smile:
It's working!
Thank you.

**Comment by aterenin** [comment]
Awesome! Glad to hear!

This package is still in very early stages, so there might be some difficulties. Please do let me know if you find any.
